### ISSUE TITLE
`Promise is undefined` console error in IE11

### ISSUE THREAD

**Issue by Blackbaud-IsaacAggrey** [blackbaud/auth-client#125]
![image](https://user-images.githubusercontent.com/5076129/73186187-f1b34400-40e4-11ea-8b48-412ae98dc855.png)

**Comment by Blackbaud-BobbyEarl** [comment]
This behavior is expected and covered in the [README prerequisites](https://github.com/blackbaud/auth-client#prerequisites).

**Comment by Blackbaud-IsaacAggrey** [comment]
Sounds good - this is in RENXT, so I'll notify on their end :man_shrugging:
