### ISSUE TITLE
Update transitive dev dependencies with security updates

### ISSUE THREAD

**Issue by Blackbaud-IsaacAggrey** [blackbaud/auth-client#91]
![Screenshot_2019-05-28 Mail - Isaac Aggrey - Outlook](https://user-images.githubusercontent.com/5076129/58496950-8291e400-8140-11e9-828d-b503584aa70f.png)

This is not all that important since these are all just dev dependencies, none of which we directly depende on, but could be a simple PR :) 

I could see this being closed but it is good to know of it as a "Won't Fix" that can be linked to.

**Comment by Blackbaud-SteveBrush** [comment]
Thanks @Blackbaud-IsaacAggrey! We've since fixed all vulnerability warnings.
